/*
This file is part of VideoRecorder v0.1

VideoRecorder is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

VideoRecorder is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with VideoRecorder.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * VideoRecorderGUI.java
 *
 * Created on Oct 5, 2012, 6:10:08 PM
 */
package com.deepak.videorecorder;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.CannotRealizeException;
import javax.media.IncompatibleSourceException;
import javax.media.NoDataSinkException;
import javax.media.NoDataSourceException;
import javax.media.NoPlayerException;

/**
 *
 * @author deepak
 */
/*
 * the class which provides the gui for the recorder
 */
public class VideoRecorderGUI extends javax.swing.JFrame {

    // the video recorder object
    private VideoRecorder videoRecorder = null;

    /** Creates new form VideoRecorderGUI */
    public VideoRecorderGUI() {
        initComponents();
        // initialise the video recorder object
        videoRecorder = new VideoRecorder();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        videoDisplayPanel = new javax.swing.JPanel();
        recordToggleButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Video Recorder");

        videoDisplayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        videoDisplayPanel.setLayout(new java.awt.BorderLayout());

        recordToggleButton.setText("Record");
        recordToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordToggleButton_MouseClickedEvent(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recordToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(videoDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recordToggleButton)
                .addGap(18, 18, 18)
                .addComponent(videoDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * method called when the record toggle button is clicked
     */
    private void recordToggleButton_MouseClickedEvent(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordToggleButton_MouseClickedEvent
        // TODO add your handling code here:
        // if the current toggle button name is record the nstart recording
        if (recordToggleButton.getText().contentEquals("Record")) {
            try {
                // start the recorder and provide a random file name for saving
                videoRecorder.startRecording("Recorded_Videos/" + new Random().nextInt(Integer.MAX_VALUE) + ".avi");
                // the video display panel must have border layout
                // for proper displaying
                // add the visual component to the panel
                videoDisplayPanel.add(videoRecorder.getVisualComponent());
            } catch (IncompatibleSourceException ex) {
                Logger.getLogger(VideoRecorderGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoDataSourceException ex) {
                Logger.getLogger(VideoRecorderGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(VideoRecorderGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoPlayerException ex) {
                Logger.getLogger(VideoRecorderGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (CannotRealizeException ex) {
                Logger.getLogger(VideoRecorderGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoDataSinkException ex) {
                Logger.getLogger(VideoRecorderGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            // set the toggle button name as stop
            recordToggleButton.setText("Stop");
        } // else stop recording
        else {
            // stop recorder
            videoRecorder.stopRecording();
            // reset the toggle button name to record
            recordToggleButton.setText("Record");
        }
    }//GEN-LAST:event_recordToggleButton_MouseClickedEvent

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VideoRecorderGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton recordToggleButton;
    private javax.swing.JPanel videoDisplayPanel;
    // End of variables declaration//GEN-END:variables
}
